name: cron run
on:
  schedule:
    - cron: '44 3 * * *'

jobs:
  build:
    name: Trigger cron action
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST https://stock-price-prediction-ix00e96gw-hgoyal09.vercel.app/cron-functions/getRealtimeStockData
