name: cron run
on:
  schedule:
    - cron: '14 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Trigger cron action
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X GET https://stock-price-prediction-dgtyjt5e0-hgoyal09.vercel.app/stock-details/TSLA
