name: dev deploy
on:
    push:
        branches: [dev]
    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.vercelToken }}
                  vercel-org-id: ${{ secrets.devVercelOrgId }}
                  vercel-project-id: ${{ secrets.devVercelProjectId }}
