name: deploy website
on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.vercelToken }}
                  vercel-org-id: ${{ secrets.vercelOrgId }}
                  vercel-project-id: ${{ secrets.vercelProjectId }}
